from .game_config import *

__all__ = ["WORLD_WIDTH", "WORLD_HEIGHT", "WORLD_ALTITUDE_FORMULA", "WORLD_TEMPERATURE_FORMULA",
           "WORLD_NUTRIENTS_FORMULA", "INITIAL_CELL_COUNT", "MAX_HEAT_INITIAL",
           "MAX_COLD_INITIAL", "MAX_HEALTH_INITIAL", "HUNGER_INITIAL", "MUTATION_RATE_INITIAL"]
