name: Static Type Checking with MyPy

on: [push, pull_request]

jobs:
  type-check:
    name: Run MyPy Type Checking
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        
    - name: Run static type checking on task1
      run: |
        mypy --strict task1/
        
    - name: Run type checking on test files
      run: |
        mypy tests/test_task1/
