name: Python CI

on: [push, pull_request]

jobs:
  test-and-typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - run: pip install pytest mypy
    - run: PYTHONPATH=$PYTHONPATH:$(pwd) pytest
    - run: PYTHONPATH=$PYTHONPATH:$(pwd) mypy . --ignore-missing-imports
