name: Run Tests

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on
  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the version of Python you want to use

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run tests
    - name: Run pytest
      run: |
        pytest
